export const allIngredients = [
	"Absolute Citron",
	"Bourbon",
	"Bourbon Bullet",
	"Jarana",
	"Martini rosso",
	"Pepsi",
	"RADA",
	"тангірі",
	"ангостура",
	"абрикос бренді",
	"бейліс лікер",
	"бітер",
	"блу курасао лікер",
	"ваніль абсолют",
	"дралбуї",
	"дольки лимону",
	"еспресо",
	"зілгентон",
	"ігристе сухе",
	"ізі фом",
	"кампарі",
	"какао лікер",
	"контрау",
	"лайм",
	"лікер кавовий",
	"мадлети",
	"моршинська",
	"м'ята",
	"пюре кокос",
	"ром білий",
	"ром темний",
	"сік ананас",
	"сік апельсин",
	"сік гранат",
	"сироп гренадин",
	"сироп карамель",
	"сироп мигдаль",
	"сироп малина",
	"сироп маракуя",
	"сироп чорниця",
	"спрайт",
	"сухе мартіні",
	"танкері",
	"тростинний цукор",
	"фреш лайм",
	"фреш лимон",
	"цукровий сироп",
];

export const cocktails = [
	{
		name: "Tasty cream",
		ingredients: [
			{ name: "бейліс лікер", amount: 30 },
			{ name: "какао лікер", amount: 30 },
			{ name: "абрикос бренді", amount: 30 },
			{ name: "фреш лимон", amount: 20 },
			{ name: "сироп мигдаль", amount: 10 },
			{ name: "ізі фом", amount: 2 },
		],
	},

	{
		name: "Sky",
		ingredients: [
			{ name: "ваніль абсолют", amount: 45 },
			{ name: "блу курасао лікер", amount: 15 },
			{ name: "пюре кокос", amount: 15 },
			{ name: "фреш лимон", amount: 15 },
			{ name: "сироп чорниця", amount: 10 },
			{ name: "вершки", amount: 20 },
			{ name: "сік ананас", amount: 30 },
		],
	},
	{
		name: "Hurricane",
		ingredients: [
			{ name: "ром білий", amount: 20 },
			{ name: "ром темний", amount: 50 },
			{ name: "сік апельсин", amount: 30 },
			{ name: "фреш лайм", amount: 30 },
			{ name: "сироп маракуя", amount: 30 },
			{ name: "сироп гренадин", amount: 5 },
		],
	},
	{
		name: "Cosmopolitan",
		ingredients: [
			{ name: "Absolute Citron", amount: 50 },
			{ name: "контрау", amount: 20 },
			{ name: "сік гранат", amount: 50 },
			{ name: "фреш лайм", amount: 15 },
		],
	},
	{
		name: "Dry-martini",
		ingredients: [
			{ name: "танкері", amount: 50 },
			{
				name: "сухе мартіні + декор з оливки",
				amount: 15,
			},
		],
	},
	{
		name: "Espresso Martini",
		ingredients: [
			{ name: "RADA", amount: 50 },
			{ name: "лікер кавовий", amount: 15 },
			{ name: "цукровий сироп", amount: 10 },
			{ name: "еспресо", amount: 30 },
		],
	},
	{
		name: "Clover Club",
		ingredients: [
			{ name: "танкері", amount: 45 },
			{ name: "сироп малина", amount: 15 },
			{ name: "фреш лимон", amount: 15 },
			{ name: "ізі фом", amount: 2 },
		],
	},
	{
		name: "Long Island icetea",
		ingredients: [
			{ name: "RADA", amount: 20 },
			{ name: "танкірі", amount: 20 },
			{ name: "ром білий", amount: 20 },
			{ name: "Jarana", amount: 20 },
			{ name: "контрау", amount: 20 },
			{ name: "дольки лимону", amount: "так" },
			{
				name: "Pepsi",
				amount: [
					70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
					87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
				],
			},
		],
	},
	{
		name: "French 75",
		ingredients: [
			{ name: "танкірі", amount: 30 },
			{ name: "фреш лимон", amount: 15 },
			{ name: "цукровий сироп", amount: 15 },
			{ name: "ігристе сухе", amount: 60 },
		],
	},
	{
		name: "Tom Colling",
		ingredients: [
			{ name: "танкері", amount: 50 },
			{ name: "фреш лайм", amount: 30 },
			{ name: "цукровий сироп", amount: 15 },
			{ name: "моршинська", amount: 30 },
		],
	},
	{
		name: "Old Fashioned",
		ingredients: [
			{ name: "тростинний цукор", amount: 2 },
			{ name: "ангостура", amount: 4 },
			{ name: "Bourbon Bullet", amount: 50 },
			{ name: "мадлети", amount: "так" },
		],
	},
	{
		name: "Мохіто",
		ingredients: [
			{ name: "ром білий", amount: 50 },
			{ name: "тростинний цукор", amount: 1 },
			{ name: "лайм", amount: 2 },
			{ name: "м'ята", amount: [5, 6, 7, 8, 9, 10] },
			{ name: "спрайт", amount: 120 },
		],
	},
	{
		name: "Маі Таі",
		ingredients: [
			{ name: "ром темний", amount: 30 },
			{ name: "ром білий", amount: 30 },
			{ name: "контроу", amount: 20 },
			{ name: "сік апельсин", amount: 35 },
			{ name: "сік ананас", amount: 35 },
			{ name: "фреш лайм", amount: 25 },
			{ name: "сироп мигдаль", amount: 10 },
			{ name: "сироп маракуя", amount: 10 },
			{ name: "сироп карамель", amount: 10 },
		],
	},
	{
		name: "Margarita",
		ingredients: [
			{ name: "Jarana", amount: 50 },
			{ name: "контроу", amount: 25 },
			{ name: "фреш лайм", amount: 30 },
			{ name: "цукровий сироп", amount: 15 },
		],
	},
	{
		name: "Boulevardier",
		ingredients: [
			{ name: "Bourbon", amount: 45 },
			{ name: "Martini rosso", amount: 30 },
			{ name: "бітер", amount: 30 },
			{ name: "ангостура", amount: 2 },
		],
	},
	{
		name: "Rusty nail",
		ingredients: [
			{ name: "сілгентон", amount: 50 },
			{ name: "дралбуї", amount: 25 },
		],
	},
	{
		name: "Americano",
		ingredients: [
			{ name: "кампарі", amount: 30 },
			{ name: "Martini rosso", amount: 30 },
			{ name: "моршинська", amount: 30 },
		],
	},
	{
		name: "Daiquiri",
		ingredients: [
			{ name: "ром білий", amount: 50 },
			{ name: "фреш лайм", amount: 30 },
			{ name: "цукровий сироп", amount: 15 },
		],
	},
];
